name: Delete Old Artifacts

on:
  schedule:
    - cron: '0 3 * * *'   # 매일 새벽 3시(UTC)에 실행

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Delete artifacts older than 1 day
        uses: actions/github-script@v7
        with:
          script: |
            const maxAge = 1 * 24 * 60 * 60 * 1000; // 1일(ms)
            const artifacts = await github.rest.actions.listArtifactsForRepo({
              owner: context.repo.owner,
              repo: context.repo.repo,
            });
            for (const artifact of artifacts.data.artifacts) {
              const created = new Date(artifact.created_at).getTime();
              if (Date.now() - created > maxAge) {
                await github.rest.actions.deleteArtifact({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  artifact_id: artifact.id,
                });
                console.log(`Deleted artifact: ${artifact.name}`);
              }
            }

